#See: 
# - https://dev.to/xaviercanchal/automatic-versioning-in-a-lerna-monorepo-using-github-actions-4hij
# - https://github.com/graphistry/pygraphistry/blob/master/.github/workflows/ci.yml

name: CI

on:
  #Regular dev
  push:
  pull_request:
    types: [opened, synchronize] # Workflow triggering events

  #Enable UI-driven branch testing
  workflow_dispatch:

  #Test main bidaily @ 1a
  schedule:
    - cron: '0 1 1-31/2 * *'


jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Build and lint"
      run: |
        docker-compose build

    - name: "JSDocs"
      run: |
        ./tools/jsdocs.sh
        du -sh ./docs-build/jsdocs

    - name: "Storybook"
      run: |
        ./tools/storybook.sh
        du -sh ./docs-build

    - name: "Ensure binaries"
      run: |
        ./tools/extract-dist.sh
